### ISSUE TITLE
Update is installed incorrectly

### ISSUE THREAD

**Issue by lucryptoin** [futurumclix/futurumclix#4]
I use paid version of script with encrypted files. Update to cancel license can not be installed. Addons can not be activated. Also in Fresh template do not work Login Ads, Explorer Ads and there are other bugs. 
Will you help me fix errors and install update?

**Comment by lucryptoin** [comment]
From the official website I was sent here. 
I have installed Licence ID #109 Beginner. Expires on Mon, Dec 10th 2018 with 20170516 update. 
Modules attached to my Licence #109 Bot System & Copyright Removal
Last updated repealing the license is not installed. Can't install other add-ons. The script always requires a license.
Server linux, x86_64, PHP Version 5.4.45, 
MySQL Version 10.1.24-MariaDB-cll-lve
What information is still needed?
I'm not a programmer but an ordinary buyer of the script.

**Comment by futurumclix** [comment]
As far as I know the licence.php file will be still needed, because ionCube extension needs it to decrypt the files. Last update removed checks for licenses for modules & translations, so now you can freely install any modules and translations available.
If you already have version 20170516, everything you need is to install last update (20171211_20180116) by unpacking it content to installation directory and overwriting all files.
Please also note the script requires PHP in version 5.6 and you have 5.4.45. You should update it.
If you would like to remove need of licence.php file you can install FuturumClix from the free ([AGPLv3](https://github.com/futurumclix/futurumclix/blob/master/LICENSE)) release available in [releases section](https://github.com/futurumclix/futurumclix/releases) of this repository.
If you have errors after installing 20171211_20180116 package, please enable debug mode and post messages from /app/tmp/logs/error.log file (last 20-40 lines should be enough).

**Comment by lucryptoin** [comment]
As I wrote above, the update does not solve the problem with the license. Addons do not work.

**Comment by futurumclix** [comment]
Can you be more descriptive? What do you mean by "Addons do not work"? You can't enable one? Is there any message when you try? Can you tell me which one you tried, so I can check it myself?

**Comment by lucryptoin** [comment]
I installed the update. Then I wanted to activate the addon. Leave a message on white background:
The encoded file has included a file which is either non-encoded or has incorrect properties.
So any addons.
Can you check it out? How to give you login detalis for C-panel?

**Comment by futurumclix** [comment]
It looks like you have tried to install an non-encoded module, it won't work that way. If you have encoded script, you need to install an encoded version of module.

**Comment by lucryptoin** [comment]
I wanted to buy them but support told me that I can activate the modules for free. I don't have encoded modules. Does this mean that I can't already add modules?

**Comment by futurumclix** [comment]
Oh, now I can see where is problem. :-) I don't know if I can host the packages on GitHub, so I will ask tomorrow about that. I will let you know as soon as I got answer.

**Comment by lucryptoin** [comment]
Thanks for hope!

**Comment by futurumclix** [comment]
Unfortunately I can't host packages here, but they should be now available to download from the shop site, along with the modules you has bought earlier. Please let me know if you can download and install modules you wanted, so I can close this issue.

**Comment by lucryptoin** [comment]
Yes, all right. Modules activated successfully, thank you. And one more question before closing issue. 
Now the purchased script is not supported?
Just in Fresh template do not work Login Ads, Explorer Ads and there are other bugs.

**Comment by futurumclix** [comment]
Yes, probably the encrypted versions will not be supported any longer, but I don't know for sure. Anything can happen. :-) I would strongly recommend you to upgrade to unencrypted version.
If you know about any bugs, please open another issue (one per bug, as it will be better for me to work that way, and also better for you - when I fix something you can look at commit and check what exactly needs to be changed). I will try to make fixes more in the views files (they are unencrypted, so you can edit them), but that's only where it would be possible.
